sources:
  - /streams/sample_720p.h264
  - /streams/sample_720p_copy.h264

streammux:
  width: 1280
  height: 720

pgie:
  config_file: config_pgie_rfdetr_nano.txt
  network_width: 384
  network_height: 384
  conf_threshold: 0.5
  labels_file: /models/rfdetr/labels.txt

tracker:
  config_file: config_tracker.txt

rtsp:
  port: 8554
  udp_port: 5400
  mount: /stream
  codec: H264
  bitrate: 4000000
  enc_type: 0
