sources:
  - /streams/sample_720p.h264
  - rtsp://admin:Galor555@10.0.0.181:554/Streaming/Channels/101

streammux:
  width: 1280
  height: 720

pgie:
  config_file: config_pgie_yolo26_x.txt

tracker:
  config_file: config_tracker.txt

rtsp:
  port: 8554
  udp_port: 5400
  mount: /stream
  codec: H264
  bitrate: 4000000
