################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

services:
  ms-nvclip:
    build:
      context: nvclip
      target: builder_base
      dockerfile: Dockerfile
    image: ms-nvclip
    volumes:
      - '~/.cache/model-repo/:/workspace/model-repo'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      NGC_API_KEY: ""
#      DEBUG: 1
  ms-changenet:
    build:
      context: changenet
      target: builder_base
      dockerfile: Dockerfile
    image: ms-changenet
    volumes:
      - '~/.cache/model-repo/visual_changenet:/workspace/model_repo/visual_changenet/1'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      HTTP_PORT: 8003
      DEBUG: 0
  tao-cv:
    user: nvs:1000
    build:
      context: tao
      target: cv_tao_base
      dockerfile: Dockerfile
    image: tao-cv
    # entrypoint: ["/bin/bash"]
    # # Keep container running
    # command: ["-c", "sleep infinity"]
    volumes:
      - '~/.cache/model-repo/:/workspace/.cache/model-repo'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      DEBUG: 0
      TAO_MODEL_NAME: rtdetr
  dry-run:
    user: nvs:1000
    build:
      context: dummy
      target: inference_base
      dockerfile: Dockerfile
    image: dry-run
    volumes:
      - '~/.cache:/workspace/.cache'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      DEBUG: 1
  ms-qwen:
    build:
      context: qwen
      target: inference_base
      dockerfile: Dockerfile
    image: ms-qwen
    volumes:
      - '~/.cache/model-repo:/workspace/model-repo'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      DEBUG: 0
  ms-vllm:
    build:
      context: vllm
      target: inference_base
      dockerfile: Dockerfile
    image: ms-vllm
    volumes:
      - '~/.cache/model-repo:/workspace/model-repo'
    ipc: host
    # init: true
    ports:
      - "8800-8803:8000-8003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              #count: 1
              capabilities: [gpu]
    environment:
      DEBUG: 0
      # number of codec instances based on the hardware specification
      N_CODEC_INSTANCES: 7
